# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('url', models.URLField()),
            ],
        ),
    ]
