# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170324_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdirection',
            name='code',
            field=models.CharField(default='0', max_length=255, verbose_name='код'),
        ),
    ]
