# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_trainingdirection_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingdirection',
            options={'verbose_name': 'направление подготовки ФГОС', 'verbose_name_plural': 'направления подготовки ФГОС'},
        ),
        migrations.AlterModelOptions(
            name='trainingdirectiongroup',
            options={'verbose_name': 'группа направлений подготовки ФГОС', 'verbose_name_plural': 'группы направлений подготовки ФГОС'},
        ),
        migrations.AddField(
            model_name='trainingdirection',
            name='type',
            field=models.CharField(choices=[('s', 'специалист'), ('b', 'бакалавр'), ('m', 'магистр')], default='b', max_length=1, verbose_name='уровень'),
        ),
    ]
