# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_trainingdirection_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='интро')),
                ('salary', models.IntegerField(default=0, verbose_name='средняя зарплата')),
            ],
            options={
                'verbose_name_plural': 'специальности',
                'verbose_name': 'специальность',
            },
        ),
        migrations.CreateModel(
            name='SpecialtyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name_plural': 'группы специальностей',
                'verbose_name': 'группа специальностей',
            },
        ),
        migrations.AddField(
            model_name='specialty',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SpecialtyGroup'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='training_directions',
            field=models.ManyToManyField(to='app.TrainingDirection'),
        ),
    ]
