# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170331_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'кафедры',
                'verbose_name': 'кафедра',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbr', models.CharField(max_length=127)),
                ('site', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'институты/факультеты',
                'verbose_name': 'институт/факультет',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbr', models.CharField(max_length=127)),
                ('site', models.URLField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.City')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='app.University')),
            ],
            options={
                'verbose_name_plural': 'ВУЗы',
                'verbose_name': 'ВУЗ',
            },
        ),
        migrations.AddField(
            model_name='subdivision',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.University'),
        ),
        migrations.AddField(
            model_name='department',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subdivision'),
        ),
    ]
