# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170403_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='hide',
            field=models.BooleanField(default=True, verbose_name='скрыт'),
        ),
    ]
