# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_university_hide'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название социальной сети')),
            ],
            options={
                'verbose_name': 'сслыка на социальную сеть',
                'verbose_name_plural': 'ссылки на социальные сети',
            },
        ),
    ]
