# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170503_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='social_links',
        ),
    ]
