# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_university_social_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
