# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511, verbose_name='название')),
                ('source', models.URLField(verbose_name='адрес источника')),
                ('year', models.IntegerField(verbose_name='год сбора информации')),
            ],
        ),
        migrations.CreateModel(
            name='RatingPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='позиция в рейтинге')),
                ('rating', models.ManyToManyField(related_name='рейтинг', to='app.Rating')),
                ('university', models.ManyToManyField(related_name='университет', to='app.University')),
            ],
        ),
    ]
