# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rating_ratingposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingposition',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='ratingposition',
            name='university',
        ),
        migrations.DeleteModel(
            name='RatingPosition',
        ),
    ]
