# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_ratingposition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingposition',
            options={'verbose_name': 'позиция в рейтинге', 'verbose_name_plural': 'позиции в рейтинге'},
        ),
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(default='logo_default.png', upload_to='university_logo'),
        ),
    ]
