# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20170510_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(default='logo_default.png', upload_to='university_logo/'),
        ),
    ]
