# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 07:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20170511_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinkUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.University')),
            ],
            options={
                'verbose_name': 'именованая ссылка',
                'abstract': False,
                'verbose_name_plural': 'именованные ссылки',
            },
        ),
    ]
