# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_sociallinkuniversity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialLinkUniversity',
            new_name='NamedLinkUniversity',
        ),
    ]
