# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20170511_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedlinkuniversity',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
